[package]
name = "agglayer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-appender = "0.2.3"
clap = { version = "4.4.6", features = ["derive", "env"] }
anyhow = "1.0.81"
dotenvy = "0.15.7"
toml = "0.8.12"
serde = { version = "1.0.197", features = ["derive"] }
url = { version = "2.5.0", features = ["serde"] }
thiserror = "1.0.58"
futures = "0.3.30"
jsonrpsee = { version = "0.22.3", features = ["full"] }
serde_with = "3.7.0"
async-trait = "0.1.80"
hex = "0.4.3"

# Gcloud SDK to communicate with Google Cloud KMS
gcloud-sdk = { version = "0.24", features = ["google-cloud-kms-v1"] }

alloy = { git = "https://github.com/alloy-rs/alloy", rev = "188c4f8", features = [
    "contract",
    "network",
    "node-bindings",
    "providers",
    "provider-http",
    "provider-ipc",
    "provider-ws",
    "rpc-client",
    "rpc-client-ipc",
    "rpc-client-ws",
    "rpc-types-eth",
    "rpc-types-trace",
    "signers",
    "signer-gcp",
    "signer-keystore",
    "signer-ledger",
    "signer-mnemonic",
    "signer-trezor",
    "signer-wallet",
    "signer-yubihsm",
    "sol-types",
] }
