[package]
name = "agglayer-signer"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
ethers-gcp-kms-signer.workspace = true
ethers.workspace = true
thiserror.workspace = true

agglayer-gcp-kms = { path = "../agglayer-gcp-kms" }
