[package]
name = "agglayer-signer"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
ethers-gcp-kms-signer.workspace = true
ethers.workspace = true
thiserror.workspace = true
