name: Docker

on:
  push:
    branches: [main, fix/run-kurtosis-cdk]
  pull_request:
    branches: [main]
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docker:
    uses: ./.github/workflows/util:docker.yml
    secrets: inherit
    with:
      push: true
