name: Kurtosis-CDK

env:
  LOCAL_ARTIFACT_NAME: docker-image
  LOCAL_ARTIFACT_DIR: /tmp

on:
  push:
    branches: [main, ci/run-kurtosis-cdk]
  pull_request:
    branches: [main]
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docker:
    uses: ./.github/workflows/util:docker.yml
    secrets: inherit
    with:
      push: false
      local-artifact-name: "docker-image"
      local-artifact-dir: "/tmp"

  kurtosis-cdk:
    name: Kurtosis-CDK
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: "docker-image"
          path: "/tmp"

      - name: Load image
        run: |
          echo ${{ needs.docker.outputs.tags }}
          docker load --input /tmp/docker-image.tar
          docker image ls -a

      - name: Checkout agglayer-rs
        uses: actions/checkout@v4

      - name: Checkout kurtosis-cdk
        uses: actions/checkout@v4
        with:
          repository: 0xpolygon/kurtosis-cdk
          ref: main'
          path: kurtosis-cdk

      - name: Use local agglayer-rs docker img
        working-directory: kurtosis-cdk
        run: |
          file="params.yml"
          key="zkevm_agglayer_image"
          new_value="${{ needs.docker.outputs.tags }}"

          # Escape special characters in the new value
          escaped_new_value=$(sed 's/[\/&]/\\&/g' <<< "$new_value")

          sed -i "s/^\($key\s*=\s*\).*$/\1$escaped_new_value/" "$file"

          # Debug
          cat params.yml

      - name: Install kurtosis
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli
          kurtosis analytics disable
