name: Kurtosis-CDK

env:
  LOCAL_ARTIFACT_NAME: docker-image
  LOCAL_ARTIFACT_DIR: /tmp

on:
  push:
    branches: [main, ci/run-kurtosis-cdk]
  pull_request:
    branches: [main]
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docker:
    uses: ./.github/workflows/util:docker.yml
    secrets: inherit
    with:
      push: false
      local-artifact-name: "docker-image"
      local-artifact-dir: "/tmp"

  kurtosis-cdk:
    name: Kurtosis-CDK
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: "docker-image"
          path: "/tmp"

      - name: Load image
        run: |
          echo ${{ needs.docker.outputs.tags }}
          docker load --input /tmp/docker-image.tar
          docker image ls -a

      - name: Checkout agglayer-rs
        uses: actions/checkout@v4

      - name: Checkout kurtosis-cdk
        uses: actions/checkout@v4
        with:
          repository: 0xpolygon/kurtosis-cdk
          ref: main
          path: kurtosis-cdk

      - name: Replace param with local agglayer-rs docker img
        run: |
          cd kurtosis-cdk
          new_value="${{ needs.docker.outputs.tags }}"

          # Escape special characters in the new value
          escaped_new_value=$(sed 's/[\/&]/\\&/g' <<< "$new_value")

          sed -i "s/zkevm_agglayer_image: .*/zkevm_agglayer_image: $escaped_new_value/" "params.yml"

          # Debug
          cat params.yml

      - name: Install kurtosis
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli
          kurtosis analytics disable

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run kurtosis
        run: |
          cd kurtosis-cdk
          kurtosis run --enclave cdk-v1 --args-file params.yml --image-download always .

      - name: Expose RPC URL
        run: echo "ETH_RPC_URL=$(kurtosis port print cdk-v1 zkevm-node-rpc-001 http-rpc)" >> $GITHUB_ENV

      - name: Check that batches are progressing
        env:
          COMMAND: "cast rpc zkevm_batchNumber && cast rpc zkevm_virtualBatchNumber && cast rpc zkevm_verifiedBatchNumber"
          ETH_RPC_URL: ${{ env.ETH_RPC_URL }}
          INTERVAL_SECONDS: 5
          TIMEOUT_SECONDS: 60
        run: >
          ./.github/workflows/scripts/are_counters_progressing.sh
          $COMMAND
          $TIMEOUT_SECONDS
          $INTERVAL_SECONDS
